name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build shared package
        run: npm run -w @logilite/shared build

      
      - name: Typecheck shared
        run: npm run -w @logilite/shared typecheck